# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "Mausy5043-bot"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # or GitHub Actions, set the directory to / to check for workflow files in .github/workflows.
    directory: '/'
    target-branch: "Mausy5043-bot"
    schedule:
      interval: 'daily'

  # Enable version updates for python
  - package-ecosystem: 'pip'
  # Look for `requirements.txt` file
    directory: '/'
    target-branch: "Mausy5043-bot"
    schedule:
      interval: 'daily'
